Add new completion API (#866)
* Don't trigger AC on word_separators

* Add back complete_all_chars

* fix pycodestyle error

* Update plugin/completion.py

Co-Authored-By: Raoul Wols <r@primef.actor>

* Remove ignored_trigger_chars

* Integrate new completion api

* fix typo

* Support snippets

* Insert textEdit completion,

Dont replace them

* update text icon and remove unused function

* FIX AttributeError: module 'asyncio' has no attribute 'get_running_loop'

* Use text edit Range

* use text edit range

* make flake and mypy happy

* Add typings and remove unused class property

* When choosing a completion item the typed text (prefix) will be deleted and that the completion item text will be inserted,

But because edit_region.end() will take in account the previously typed text(the prefix), which is erased, we wont be using the end edit region. because it deletes some lines that it shouldn't, so we use the current_point as the end of the edit Region

* Add cache

* Ignore mypy error instead of casting a type

* revert back timeout

* Remove committing flag

* better comment

* revert accidentally committed code

* remove last_text_command as it is not necessary

* remove completion_hint_type setting

* remove quotes from types

* Use text_edit['range'].end and remove duplicated functions

* Skip calculating the offset by inserting the removed prefix first. And don't touch selections.

* Add types and remove trigger_chars from instance properties

* Fix flake

* remove auto_complete_selector

* Handle multiple cursor completions

* Can be(will be probably) reverted. This is my try to fix the completion tests.

* Change keyword icon "κ" to something that looks like a key => "☌"

* Revert "Change keyword icon "κ" to something that looks like a key => "☌""

This reverts commit 316d29d7cddc4a148ad6de0b6eb2685ef3c2ab9e.

* Remove if check for document_position

* fix typo

* erase regoion for snippet, replace region for plain text

* don't allocate a dict

* remove indent

* fix other failing tests

* Use set_response and await_message in favour of test_compmpletion property on CompletionHandler

* Send a resolve request only if we don't have apply_additional_edits on the completion item

Ideally we would send the resolveCompletionItem request if it higlighted in the autocomplete popup, but currently there is no api for that.
For now we use the resove completion item just to apply additional_text_edits after the completion item is selected.

* Add E2E tests for prefering insert text over label and text edit over insert text

Some tests in test_completions_core like:
- test_text_edit_clangd
- test_text_edit_intelephense
- test_use_label_as_is

are removed becasuse they are not relevant anymore

tests like
- test_only_label_item
- test_prefers_insert_text

are moved to test_completions and are tested in a E2E test fashion

* add test to apply additional edits only one time

* set "auto_complete_preserve_order" to "none" in tests

* make mypy and pyflake happy

* Remove "complete_all_chars" setting in favor of sublime default "auto_complete" setting

* Add test for intelephense

* remove old completion samples

* Fix sublime removing $ from the prefix

* Revert "erase regoion for snippet, replace region for plain text"

This reverts commit 44a3b2a36a87436a34a82b9c2fa2ee9c48492b83.

* Workaround for TextEdit range not being valid when selection a completion item

The workaround works like this.

First a fact: "The specs says that a TextEdit must span only on one line".

when we request completion items.
and get a response.

We save each line where a cursor is.
When we select a command completion item.
The text is deleted.

But becuse we saved the line contents before, we just restore it. so we have the state as before.

This workaround have one big downside, I guess it wouldn't work performant for lines that are really really really long.

* Better handle multicursor text edits

* Move save lines to on_query_completions, and clean up the a little

* make flake8 and mypy happy

* fix typo

* Dont use static class variables for saving the Line contents, because each request to the server will override the previous state.

instead create instances so each request has its own independent Line state, and the request cannot override the previous state.

* fix for commit_completion re-triggers the completion panel "forever"

* Better handle multicursor text edits

* use transform_region to restore file contents

* Resolve the completion promise in the handle_error

* remove hiding auto_complete gloably after commit_completions

Co-authored-by: Raoul Wols <r@primef.actor>
Co-authored-by: Predrag Nikolic <predrag.nikolic@codetri.be>