Squashed commit of the following:
commit 09d5f319803e4ea08cfc70001a898a3c471d480b
Author: Tom van Ommeren <tom.vanommeren@gmail.com>
Date:   Mon Feb 5 22:54:50 2018 +0100

    Small fixes before merging

    - don't cache client in hover.py (risk to client restart functionality)
    - improvement: show diagnostics hovers even if no hoverProvider capability.
    - remove unneeded event param additions in main.py
    - restore is_at_word in definition.py

commit 36e339b38b0060926f763df49ea93ab208121397
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Mon Feb 5 05:53:09 2018 -0200

    Passed event to is_at_word(self.view, event)

commit ac5e228af94bf5b6fe8b63a5243ca48cae00440f
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Mon Feb 5 00:38:18 2018 -0200

    Added missing return on plugin/symbols.py

commit 45170abc93dc591426c9fc7f9df197455b4c127c
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 22:08:22 2018 -0200

    TypeError: is_enabled() got an unexpected keyword argument 'point'

commit 1a8cd9acbf687d68f4e5229c2ed1f8a17b03c6e1
Merge: 887a480 bf6a5b4
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 20:12:10 2018 -0200

    Merge branch 'master' into smart_context_menu

commit 887a480ea8ce406a2408669d92040ce5c8c98f44
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 20:09:12 2018 -0200

    Moved capability from LspTextCommand constructor to

    has_client_with_capability().

commit c790187f4824a3e9222bdd10220c0a1fadbcddc4
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 19:52:15 2018 -0200

    Fixed clients.py:54:1: E302 expected 2 blank lines, found 1

commit 12bd20965313dd5bd4cd80fb1baa37f0be79a12c
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 19:49:37 2018 -0200

    Fixed hover.py:51: error: Name 'client_for_view' is not defined

commit c314e37ff900aa77536c722ceb8492f45d84cc6d
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 19:22:21 2018 -0200

    Implemented is_enabled() on all derived classes.

commit 6b23fec638a347fa62f8ccb01b00f2c6c958c59f
Merge: 5519535 3bc9cca
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sun Feb 4 15:39:24 2018 -0200

    Merge branch 'master' into smart_context_menu

commit 551953591ccfa51fbc2f98d721a7e05ec66af1bc
Merge: 544d487 b6a3b9d
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Sat Feb 3 20:19:19 2018 -0200

    Merge branch 'master' into smart_context_menu

commit 544d487c16745dba2d7d02377c0f45aabda9ecf2
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Fri Feb 2 14:18:43 2018 -0200

    Replaced Python 2 super(...) call style by Python 3 super()

commit 598a0f6152fd1654e090389a615d4e1d68cbee6c
Merge: e4e5929 7ef8268
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Fri Feb 2 14:09:52 2018 -0200

    Merge branch 'master' into smart_context_menu

commit e4e59291835fe64602593b2387f755e105b0d250
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Thu Feb 1 23:39:18 2018 -0200

    Removed the mixing to simply code reading, writing and remove the

    mypy error: mypy -p plugin
    clients.py:26: error: Too many arguments for "__init__" of "object"

commit 0a397e3df4dbea9114d0aefc6539be84de62e73e
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Thu Feb 1 19:30:02 2018 -0200

    Fix clients.py 'sublime_plugin.TextCommand' imported but unused

commit af5bb114ff08027eb507d3a7d2816f929c47e97d
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Wed Jan 31 23:06:16 2018 -0200

    Created a mixing with TextCommand and LspTextCommand, issue:

    Not add base classes to its internal `text_command_classes` and etc variables
    https://github.com/SublimeTextIssues/Core/issues/2175

commit b0f6de3bc73ec09645e7b45502dcaaba280d93f2
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Wed Jan 31 21:52:10 2018 -0200

    Added is_enabled() to LspTextCommand base class.

commit 18d080aa48f29ee0cc1b5aec1b5198bf4f31f1cf
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Wed Jan 31 19:25:04 2018 -0200

    Renamed LspContextMenu to LspTextCommand on configurations.py

commit a192796a804df2fee44bbadd7f28dc370b4389bc
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Tue Jan 30 20:35:15 2018 -0200

    Fixed The command "mypy -p plugin" exited with 0.

    1.94s$ flake8 --exclude=./boot.py
    ./plugin/code_actions.py:2:1: F401 'sublime_plugin' imported but unused
    ./plugin/definition.py:2:1: F401 'sublime_plugin' imported but unused
    ./plugin/formatting.py:1:1: F401 'sublime_plugin' imported but unused
    ./plugin/references.py:3:1: F401 'sublime_plugin' imported but unused
    ./plugin/rename.py:1:1: F401 'sublime_plugin' imported but unused
    ./plugin/symbols.py:1:1: F401 'sublime_plugin' imported but unused

commit 31f435c75280190cfde1505fe83a7751bb7c970e
Author: evandrocoan <evandrocoan@hotmail.com>
Date:   Tue Jan 30 20:26:02 2018 -0200

    Hide Context.sublime-menu when working on projects without language

    servers